import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ACS Streams",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-neutral-950 bg-[radial-gradient(ellipse_80%_100%_at_50%_-10%,rgba(120,119,198,0.5),rgba(255,255,255,0))]`}>
        <div className="navbar bg-black opacity-25 filter backdrop-blur-sm text-gray-100">
          <div className="flex-1">
            <a className="btn btn-ghost text-xl">ACS-Stream</a>
          </div>
          <div className="flex-none">
            <ul className="menu menu-horizontal px-1">
              <li><a>Link</a></li>
              <li>
                <details>
                  <summary>Parent</summary>
                  <ul className="bg-base-100 rounded-t-none p-2">
                    <li><a>Link 1</a></li>
                    <li><a>Link 2</a></li>
                  </ul>
                </details>
              </li>
            </ul>
          </div>
        </div>
        <div className="w-[100%] min-h-[100vh] overflow-x-auto">
          {children}
        </div>
      </body>
    </html>
  );
}
